export const SHAPEFILE_CONSTANTS = {
  // Format constants
  HEADER_LENGTH: 100,
  RECORD_HEADER_LENGTH: 8,
  FILE_CODE: 9994,
  VERSION: 1000,

  // Shape type constants
  SHAPE_NULL: 0,
  SHAPE_POINT: 1,
  SHAPE_POLYLINE: 3,
  SHAPE_POLYGON: 5,
  SHAPE_MULTIPOINT: 8,
  SHAPE_POINTZ: 11,
  SHAPE_POLYLINEZ: 13,
  SHAPE_POLYGONZ: 15,
  SHAPE_MULTIPOINTZ: 18,
  SHAPE_POINTM: 21,
  SHAPE_POLYLINEM: 23,
  SHAPE_POLYGONM: 25,
  SHAPE_MULTIPOINTM: 28,
  SHAPE_MULTIPATCH: 31,

  // Geometry type flags
  HAS_Z: 0x80000000,
  HAS_M: 0x40000000
} as const;
